<?php
			if( function_exists('acf_add_local_field_group') ):

                acf_add_local_field_group(array(
                    'key' => 'group_6153b1709ca6c',
                    'title' => 'Home',
                    'fields' => array(
                        array(
                            'key' => 'field_6153b1995ba97',
                            'label' => 'Hero',
                            'name' => 'hero',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'row',
                            'acfe_seamless_style' => 1,
                            'acfe_group_modal' => 0,
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6153b1a45ba98',
                                    'label' => 'Título',
                                    'name' => 'titulo',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_6153b1ab5ba99',
                                    'label' => 'Descrição',
                                    'name' => 'descricao',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => '',
                                    'acfe_textarea_code' => 0,
                                ),
                                array(
                                    'key' => 'field_6153b1b65ba9a',
                                    'label' => 'Botão',
                                    'name' => 'botao',
                                    'type' => 'link',
                                    'instructions' => 'O texto do link é o título.',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                ),
                                array(
                                    'key' => 'field_6153b1c85ba9b',
                                    'label' => 'Imagem',
                                    'name' => 'imagem',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'uploader' => '',
                                    'acfe_thumbnail' => 0,
                                    'return_format' => 'array',
                                    'preview_size' => 'medium',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                    'library' => 'all',
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_6153b1d75ba9c',
                            'label' => 'Sobre',
                            'name' => 'sobre',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'row',
                            'acfe_seamless_style' => 0,
                            'acfe_group_modal' => 0,
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6153b1e05ba9d',
                                    'label' => 'Título',
                                    'name' => 'titulo',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_6153b1e85ba9e',
                                    'label' => 'Descrição',
                                    'name' => 'descricao',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'basic',
                                    'media_upload' => 0,
                                    'delay' => 0,
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_6153b1f55ba9f',
                            'label' => 'Serviços',
                            'name' => 'servicos',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'row',
                            'acfe_seamless_style' => 0,
                            'acfe_group_modal' => 0,
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6153b2055baa0',
                                    'label' => 'Título',
                                    'name' => 'titulo',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_6153b20a5baa1',
                                    'label' => 'Descrição',
                                    'name' => 'descricao',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => '',
                                    'acfe_textarea_code' => 0,
                                ),
                                array(
                                    'key' => 'field_6153b2125baa2',
                                    'label' => 'Lista de Serviços',
                                    'name' => 'lista_servicos',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'acfe_repeater_stylised_button' => 0,
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'row',
                                    'button_label' => '',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_6153b2245baa3',
                                            'label' => 'Ícone',
                                            'name' => 'icone',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'uploader' => '',
                                            'acfe_thumbnail' => 0,
                                            'return_format' => 'array',
                                            'preview_size' => 'medium',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                            'library' => 'all',
                                        ),
                                        array(
                                            'key' => 'field_6153b22b5baa4',
                                            'label' => 'Título',
                                            'name' => 'titulo',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                        array(
                                            'key' => 'field_6153b2305baa5',
                                            'label' => 'Descrição',
                                            'name' => 'descricao',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => '',
                                            'acfe_textarea_code' => 0,
                                        ),
                                    ),
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_6153b23d5baa6',
                            'label' => 'Depoimentos',
                            'name' => 'depoimentos',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'row',
                            'acfe_seamless_style' => 0,
                            'acfe_group_modal' => 0,
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6153b2495baa7',
                                    'label' => 'Título',
                                    'name' => 'titulo',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_6153b24e5baa8',
                                    'label' => 'Lista de Depoimentos',
                                    'name' => 'lista_depoimentos',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'acfe_repeater_stylised_button' => 0,
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'row',
                                    'button_label' => '',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_6153b25a5baa9',
                                            'label' => 'Frase',
                                            'name' => 'frase',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => '',
                                            'acfe_textarea_code' => 0,
                                        ),
                                        array(
                                            'key' => 'field_6153b2665baaa',
                                            'label' => 'Foto',
                                            'name' => 'foto',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'uploader' => '',
                                            'acfe_thumbnail' => 0,
                                            'return_format' => 'array',
                                            'preview_size' => 'medium',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                            'library' => 'all',
                                        ),
                                        array(
                                            'key' => 'field_6153b26c5baab',
                                            'label' => 'Nome / Profissão',
                                            'name' => 'nome_profissao',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'page_type',
                                'operator' => '==',
                                'value' => 'front_page',
                            ),
                        ),
                    ),
                    'menu_order' => 0,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'left',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => array(
                        0 => 'block_editor',
                        1 => 'the_content',
                        2 => 'excerpt',
                        3 => 'discussion',
                        4 => 'comments',
                        5 => 'revisions',
                        6 => 'slug',
                        7 => 'author',
                        8 => 'format',
                        9 => 'page_attributes',
                        10 => 'featured_image',
                        11 => 'categories',
                        12 => 'tags',
                        13 => 'send-trackbacks',
                    ),
                    'active' => true,
                    'description' => '',
                    'acfe_display_title' => '',
                    'acfe_autosync' => '',
                    'acfe_form' => 0,
                    'acfe_meta' => '',
                    'acfe_note' => '',
                ));
                
                endif;		