<?php
			if( function_exists('acf_add_local_field_group') ):

                acf_add_local_field_group(array(
                    'key' => 'group_61539c2b921da',
                    'title' => 'Opções',
                    'fields' => array(
                        array(
                            'key' => 'field_61539c3bfe4b5',
                            'label' => 'Redes Sociais',
                            'name' => 'social_network',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'acfe_repeater_stylised_button' => 0,
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_61539c5bfe4b7',
                                    'label' => 'Ícone',
                                    'name' => 'icone',
                                    'type' => 'text',
                                    'instructions' => 'Selecione a \'class\' do dashicon desejado. <a href="https://developer.wordpress.org/resource/dashicons/#icons-social">Saiba mais</a>.',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => 'dashicons-facebook-alt',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_61539cd0fe4b8',
                                    'label' => 'Link',
                                    'name' => 'link',
                                    'type' => 'text',
                                    'instructions' => 'Defina o destino do link.',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_61539d17a2cef',
                            'label' => 'Informações',
                            'name' => 'footer_info',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'row',
                            'acfe_seamless_style' => 0,
                            'acfe_group_modal' => 0,
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_61539d35a2cf0',
                                    'label' => 'Logo',
                                    'name' => 'logo',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'uploader' => '',
                                    'acfe_thumbnail' => 0,
                                    'return_format' => 'url',
                                    'preview_size' => 'medium',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                    'library' => 'all',
                                ),
                                array(
                                    'key' => 'field_61539d3fa2cf1',
                                    'label' => 'Telefone',
                                    'name' => 'telephone',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_61539d50a2cf2',
                                    'label' => 'E-mail',
                                    'name' => 'email',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_61539d6ca2cf3',
                            'label' => 'Copyright',
                            'name' => 'copyright',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'row',
                            'acfe_seamless_style' => 0,
                            'acfe_group_modal' => 0,
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_61539d7da2cf4',
                                    'label' => 'Brand',
                                    'name' => 'brand',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'basic',
                                    'media_upload' => 0,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_61539d98a2cf5',
                                    'label' => 'Copyright',
                                    'name' => 'copyright',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'basic',
                                    'media_upload' => 0,
                                    'delay' => 0,
                                ),
                            ),
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'options_page',
                                'operator' => '==',
                                'value' => 'opcoes',
                            ),
                        ),
                    ),
                    'menu_order' => 0,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'left',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => true,
                    'description' => '',
                    'acfe_display_title' => '',
                    'acfe_autosync' => array(
                        0 => 'php',
                    ),
                    'acfe_form' => 0,
                    'acfe_meta' => '',
                    'acfe_note' => '',
                ));
                
                endif;			